config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  resources :item_photos
  resources :items
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :item_photos
	accepts_nested_attributes_for :item_photos

	def update_pano
	  vec = []
      self.item_photos.each do |a|
        vec << a.photo.current_path
      end
      des = Rails.public_path.join("panooo#{self.id}.jpg").to_s
      p = ProcessImage.new(vec,des)
      p.generate_pano

      update_column(:pano,"/panooo#{self.id}.jpg")
	end
end

app/models/item_photo.rb
class ItemPhoto < ApplicationRecord
   mount_uploader :photo, PhotoUploader
   belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/item_photos_controller.rb
class ItemPhotosController < ApplicationController
  before_action :set_item_photo, only: [:show, :edit, :update, :destroy]

  # GET /item_photos
  # GET /item_photos.json
  def index
    @item_photos = ItemPhoto.all
  end

  # GET /item_photos/1
  # GET /item_photos/1.json
  def show
  end

  # GET /item_photos/new
  def new
    @item_photo = ItemPhoto.new
  end

  # GET /item_photos/1/edit
  def edit
  end

  # POST /item_photos
  # POST /item_photos.json
  def create
    @item_photo = ItemPhoto.new(item_photo_params)

    respond_to do |format|
      if @item_photo.save
        format.html { redirect_to @item_photo, notice: 'Item photo was successfully created.' }
        format.json { render :show, status: :created, location: @item_photo }
      else
        format.html { render :new }
        format.json { render json: @item_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /item_photos/1
  # PATCH/PUT /item_photos/1.json
  def update
    respond_to do |format|
      if @item_photo.update(item_photo_params)
        format.html { redirect_to @item_photo, notice: 'Item photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @item_photo }
      else
        format.html { render :edit }
        format.json { render json: @item_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /item_photos/1
  # DELETE /item_photos/1.json
  def destroy
    @item_photo.destroy
    respond_to do |format|
      format.html { redirect_to item_photos_url, notice: 'Item photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item_photo
      @item_photo = ItemPhoto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_photo_params
      params.require(:item_photo).permit(:item_id, :photo)
    end
end

app/controllers/items_controller.rb
#require 'lib/process_image'
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item_photos = @item.item_photos.all
    puts action_name
    puts controller_name
  end

  # GET /items/new
  def new
    @item = Item.new
    @item_photo = @item.item_photos.build
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
      if @item.save
        params[:item_photos]['photo'].each do |a|
          @item_photo = @item.item_photos.create!(:photo => a)
        end
        @item.update_pano
        flash[:success] = "Panorama image successfully created"
        redirect_to @item
      else
        flash[:error] = "Error!!" 
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, item_photos_attributes: [:id, :item_id, :photo])
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_photos_helper.rb
module ItemPhotosHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/item_photos/_form.html.erb
<%= form_for(item_photo) do |f| %>
  <% if item_photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item_photo.errors.count, "error") %> prohibited this item_photo from being saved:</h2>

      <ul>
      <% item_photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :item_id %>
    <%= f.text_field :item_id %>
  </div>

  <div class="field">
    <%= f.label :photo %>
    <%= f.text_field :photo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/item_photos/edit.html.erb
<h1>Editing Item Photo</h1>

<%= render 'form', item_photo: @item_photo %>

<%= link_to 'Show', @item_photo %> |
<%= link_to 'Back', item_photos_path %>

app/views/item_photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Item Photos</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Photo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @item_photos.each do |item_photo| %>
      <tr>
        <td><%= item_photo.item_id %></td>
        <td><%= item_photo.photo %></td>
        <td><%= link_to 'Show', item_photo %></td>
        <td><%= link_to 'Edit', edit_item_photo_path(item_photo) %></td>
        <td><%= link_to 'Destroy', item_photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item Photo', new_item_photo_path %>

app/views/item_photos/new.html.erb
<h1>New Item Photo</h1>

<%= render 'form', item_photo: @item_photo %>

<%= link_to 'Back', item_photos_path %>

app/views/item_photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @item_photo.item_id %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @item_photo.photo %>
</p>

<%= link_to 'Edit', edit_item_photo_path(@item_photo) %> |
<%= link_to 'Back', item_photos_path %>

app/views/items/_form.html.erb
<div class = 'row'>
<div class = 'col m6 offset-m3'>
<div class="card-panel z-depth-5">

<%= form_for(@item, :html => { :multipart => true, :class => ''}) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= f.label :name, 'Enter your photo name' %>
    <%= f.text_field :name %>
  </div>

  <div class="file-field input-field">
    <%= f.fields_for(:item_photos, nil, { :class => 'file-field input-field' }) do |p| %>
        <div class="btn">
          <span>File</span>
          <%= p.file_field :photo, :multiple => true, name: "item_photos[photo][]" %>
        </div>
        <div class="file-path-wrapper">
          <input class="file-path validate" type="text" placeholder="Choose 2 or more photos from your computer">
        </div>
     <% end %>
  </div>

  <div class="actions input-field">
    <%= f.submit 'Create panorama', class: 'btn' %>
  </div>
<% end %>

</div>
</div>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="container">


  <div class="carousel">
    <% @items.each do |item| %>
    <% unless item.pano.nil? %>
    <%=link_to image_tag(item.pano, size: '300x300'),item, class: 'carousel-item'%>
    <% end %>
    <% end %>
   
  </div>

</div>

app/views/items/new.html.erb
<section id='new_pano'>
<div class='container'>
<%= render 'form', item: @item %>
</div>
</section>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<div class="row">
<div class="col m8 offset-m2">

<%= image_tag @item.pano, class: "materialboxed"%>

<h4 class='center'> <strong><%=@item.name %></strong>  </h4>
</div>
</div>
</div>

app/views/layouts/_nav.html.erb
<nav class="white" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="/" class="brand-logo">PANO</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="<%=items_url%>"><i class="material-icons left">perm_media</i>Gallery</a></li>
        <li><a href="<%=new_item_url%>"><i class="material-icons left">add</i>Create</a></li>
        <li><a href="https://github.com/dongngo0804/panorama"><i class="material-icons left">mode_edit</i>Github</a></li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="#">Navbar Link</a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Panorama</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  </head>
<% if action_name == "new" %>
  <body class="body-change">
<% else %>
  <body>
<% end %> 
    <%= render 'layouts/nav' %>
     <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
 
  <div id="index-banner" class="parallax-container">
    <div class="section no-pad-bot">
      <div class="container">
        <br><br>
        <h1 class="header center teal-text text-lighten-2">Panaroma Creator</h1>
        <div class="row center">
          <h5 class="header col s12 light">A simple image stitching tool</h5>
        </div>
        <div class="row center">
         
          <%= button_to "Create your own panaroma", new_item_path, method: :get, class: "btn-large waves-effect waves-light teal lighten-1" %>
        </div>
        <br><br>

      </div>
    </div>
    <div class="parallax"><%= image_tag 'banner2.jpg' %></div>
  </div>


  <div class="container">
    <div class="section">

      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">flash_on</i></h2>
            <h5 class="center">OpenCV framework</h5>

            <p class="light">We have used OpenCV C++ as our primary tool for implement image stitching algorithms.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">group</i></h2>
            <h5 class="center">Ruby on Rails</h5>

            <p class="light">By using ruby on rails, we have enabled user to experience a better performance as well as greate design.</p>
          </div>
        </div>

        <div class="col s12 m4">
          <div class="icon-block">
            <h2 class="center brown-text"><i class="material-icons">settings</i></h2>
            <h5 class="center">Open source</h5>

            <p class="light">We have provided detailed documentation as well as source code of the application on Github, feel free to contribute to our website.</p>
          </div>
        </div>
      </div>

    </div>
  </div>


  <div class="parallax-container valign-wrapper">
    <div class="section no-pad-bot">
      <div class="container">
        <div class="row center">
          <h5 class="header col s12 light">A modern responsive front-end framework based on Material Design</h5>
        </div>
      </div>
    </div>
    <div class="parallax"><%= image_tag 'banner1.jpg' %></div>
  </div>

  <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 center">
          <h3><i class="mdi-content-send brown-text"></i></h3>
          <h4>Contact Us</h4>
        </div>
      </div>

    </div>
  </div>


 
  <footer class="page-footer teal">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">From KHTN2014 with love</h5>
          <p class="grey-text text-lighten-4">We are a team of college students working on this project for computer vision lecture.</p>


        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Ngo Hung Dong</h5>
          <ul>
            <li><a class="white-text" href="#!">14520171@gm.uit.edu.vn</a></li>
            <li><a class="white-text" href="#!">fb.com/DongNgo1996</a></li>
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text">Truong Phuc Anh</h5>
          <ul>
            <li><a class="white-text" href="#!">14520040@gm.uit.edu.vn</a></li>
            <li><a class="white-text" href="#!">fb.com/</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      Made by Ruby on Rails + OpenCV
      </div>
    </div>
  </footer>